// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlNDyhhM6k_ucs3OaIW0UGwCIhC9hx03I',
    appId: '1:645731328274:web:1023fc1f47e527ae0393cb',
    messagingSenderId: '645731328274',
    projectId: 'multi-photo-upload',
    authDomain: 'multi-photo-upload.firebaseapp.com',
    storageBucket: 'multi-photo-upload.appspot.com',
    measurementId: 'G-02FXGF28P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBegJIl7Zevyyu-3VaTPV9qLYSWIXox1bY',
    appId: '1:645731328274:android:f684baf3db34809e0393cb',
    messagingSenderId: '645731328274',
    projectId: 'multi-photo-upload',
    storageBucket: 'multi-photo-upload.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAFHmjX3Cgp14lPnx_tiC7vHtPGn5AD1w',
    appId: '1:645731328274:ios:27c2514bd343c0600393cb',
    messagingSenderId: '645731328274',
    projectId: 'multi-photo-upload',
    storageBucket: 'multi-photo-upload.appspot.com',
    iosClientId: '645731328274-flsfcaa8i6540202a1kh081nrcfqm38e.apps.googleusercontent.com',
    iosBundleId: 'com.fredblair.multiPhot0Upload',
  );
}
